Add conditional to check if the run_id.txt file exists in WE2E_tests workflow, which is only created if the SRWA Build is successful.

diff --git a/.github/workflows/WE2E_tests.yaml b/.github/workflows/WE2E_tests.yaml
--- a/.github/workflows/WE2E_tests.yaml
+++ b/.github/workflows/WE2E_tests.yaml
@@ -29,7 +29,14 @@ jobs:
         with:
           clean: false
       - id: get_run_id
-        run: echo "::set-output name=run-id::$(cat ${{ github.workspace}}/run_id.txt)"
+        run: |
+          FILE="${{ github.workspace }}/run_id.txt"
+          if [[ -f "$FILE"]]; then 
+            echo "::set-output name=run-id::$(cat ${{ github.workspace}}/run_id.txt)"
+          else 
+            echo "SRWA Build failed"
+            exit 1 
+          fi
 
   set-matrix:
     name: Set matrix of tests from machine_suites/ci.txt 
